// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozoncp/ocp-offer-api/internal/repo (interfaces: Repo)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ozoncp/ocp-offer-api/internal/models"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// AddOffers mocks base method.
func (m *MockRepo) AddOffers(arg0 []models.Offer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOffers", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOffers indicates an expected call of AddOffers.
func (mr *MockRepoMockRecorder) AddOffers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOffers", reflect.TypeOf((*MockRepo)(nil).AddOffers), arg0)
}

// DescribeOffer mocks base method.
func (m *MockRepo) DescribeOffer(arg0 uint64) (*models.Offer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeOffer", arg0)
	ret0, _ := ret[0].(*models.Offer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeOffer indicates an expected call of DescribeOffer.
func (mr *MockRepoMockRecorder) DescribeOffer(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeOffer", reflect.TypeOf((*MockRepo)(nil).DescribeOffer), arg0)
}

// ListOffers mocks base method.
func (m *MockRepo) ListOffers(arg0, arg1 uint64) ([]models.Offer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOffers", arg0, arg1)
	ret0, _ := ret[0].([]models.Offer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOffers indicates an expected call of ListOffers.
func (mr *MockRepoMockRecorder) ListOffers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOffers", reflect.TypeOf((*MockRepo)(nil).ListOffers), arg0, arg1)
}
