version: '3.9'

services:
  database:
    image: postgres:latest
    restart: always
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: ocp-offer-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ocp_offer_api
    volumes:
      - pgdata:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: ocp-offer-zookeeper
    ports:
      - '2181:2181'
    environment:
      zk_id: '1'
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2

  kafka:
    image: confluentinc/cp-kafka
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: ocp-offer-kafka
    ports:
      - '9092:9092'
      - '9094:9094'
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:32181'
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  prometheus:
    image: prom/prometheus
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: ocp-offer-prometheus
    ports:
      - '9090:9090'
    depends_on:
      - app
    links:
      - app
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'

  jaeger:
    image: jaegertracing/all-in-one:latest
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: ocp-offer-jaeger
    ports:
      - '6831:6831/udp'
      - '16686:16686'

  mongodb:
    image: mongo:4.1
    restart: always
    volumes:
      - mongodata:/data/db

  elasticsearch:
    image: elasticsearch:7.14.0
    restart: always
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.security.audit.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m -XX:+UseG1GC
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 512M
    volumes:
      - esdata:/usr/share/elasticsearch/data

  graylog:
    image: graylog/graylog:4.1
    restart: always
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # HTTP
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp

  server:
    build: .
    restart: unless-stopped
    ports:
      - '50051:50051' # gRPC
      - '8080:8080' # Gateway
      - '9100:9100' # Metrics prometheus
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: ocp-offer-server
    depends_on:
      - database
      - kafka
    links:
      - database
      - kafka
    volumes:
      - './config.yml:/root/config.yml'

volumes:
  pgdata:
    driver: local
  esdata:
    driver: local
  graylogdata:
    driver: local
  mongodata:
    driver: local
