// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.2
// source: api/ocp-offer-api/ocp-offer-api.proto

package ocp_offer_api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Offer ...
type Offer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Grade  uint64 `protobuf:"varint,3,opt,name=grade,proto3" json:"grade,omitempty"`
	TeamId uint64 `protobuf:"varint,4,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
}

func (x *Offer) Reset() {
	*x = Offer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Offer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Offer) ProtoMessage() {}

func (x *Offer) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Offer.ProtoReflect.Descriptor instead.
func (*Offer) Descriptor() ([]byte, []int) {
	return file_api_ocp_offer_api_ocp_offer_api_proto_rawDescGZIP(), []int{0}
}

func (x *Offer) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Offer) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Offer) GetGrade() uint64 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *Offer) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

// CreateOfferV1Request - create offer. Fields are validated
type CreateOfferV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Grade  uint64 `protobuf:"varint,3,opt,name=grade,proto3" json:"grade,omitempty"`
	TeamId uint64 `protobuf:"varint,4,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
}

func (x *CreateOfferV1Request) Reset() {
	*x = CreateOfferV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOfferV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOfferV1Request) ProtoMessage() {}

func (x *CreateOfferV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOfferV1Request.ProtoReflect.Descriptor instead.
func (*CreateOfferV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_offer_api_ocp_offer_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOfferV1Request) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOfferV1Request) GetGrade() uint64 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *CreateOfferV1Request) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

// CreateOfferV1Response ...
type CreateOfferV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateOfferV1Response) Reset() {
	*x = CreateOfferV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOfferV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOfferV1Response) ProtoMessage() {}

func (x *CreateOfferV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOfferV1Response.ProtoReflect.Descriptor instead.
func (*CreateOfferV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_offer_api_ocp_offer_api_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOfferV1Response) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// MultiCreateOfferV1Request ...
type MultiCreateOfferV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offers []*CreateOfferV1Request `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
}

func (x *MultiCreateOfferV1Request) Reset() {
	*x = MultiCreateOfferV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiCreateOfferV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiCreateOfferV1Request) ProtoMessage() {}

func (x *MultiCreateOfferV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiCreateOfferV1Request.ProtoReflect.Descriptor instead.
func (*MultiCreateOfferV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_offer_api_ocp_offer_api_proto_rawDescGZIP(), []int{3}
}

func (x *MultiCreateOfferV1Request) GetOffers() []*CreateOfferV1Request {
	if x != nil {
		return x.Offers
	}
	return nil
}

// MultiCreateOfferV1Response ...
type MultiCreateOfferV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *MultiCreateOfferV1Response) Reset() {
	*x = MultiCreateOfferV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiCreateOfferV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiCreateOfferV1Response) ProtoMessage() {}

func (x *MultiCreateOfferV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiCreateOfferV1Response.ProtoReflect.Descriptor instead.
func (*MultiCreateOfferV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_offer_api_ocp_offer_api_proto_rawDescGZIP(), []int{4}
}

func (x *MultiCreateOfferV1Response) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// DescribeOfferV1Request - get offer by `offer_id`. Fields are validated
type DescribeOfferV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OfferId uint64 `protobuf:"varint,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
}

func (x *DescribeOfferV1Request) Reset() {
	*x = DescribeOfferV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeOfferV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeOfferV1Request) ProtoMessage() {}

func (x *DescribeOfferV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeOfferV1Request.ProtoReflect.Descriptor instead.
func (*DescribeOfferV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_offer_api_ocp_offer_api_proto_rawDescGZIP(), []int{5}
}

func (x *DescribeOfferV1Request) GetOfferId() uint64 {
	if x != nil {
		return x.OfferId
	}
	return 0
}

// DescribeOfferV1Response ...
type DescribeOfferV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offer *Offer `protobuf:"bytes,1,opt,name=offer,proto3" json:"offer,omitempty"`
}

func (x *DescribeOfferV1Response) Reset() {
	*x = DescribeOfferV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DescribeOfferV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeOfferV1Response) ProtoMessage() {}

func (x *DescribeOfferV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeOfferV1Response.ProtoReflect.Descriptor instead.
func (*DescribeOfferV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_offer_api_ocp_offer_api_proto_rawDescGZIP(), []int{6}
}

func (x *DescribeOfferV1Response) GetOffer() *Offer {
	if x != nil {
		return x.Offer
	}
	return nil
}

// ListOfferV1Request - Fields are validated
type ListOfferV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *PaginationInput `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (x *ListOfferV1Request) Reset() {
	*x = ListOfferV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOfferV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfferV1Request) ProtoMessage() {}

func (x *ListOfferV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfferV1Request.ProtoReflect.Descriptor instead.
func (*ListOfferV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_offer_api_ocp_offer_api_proto_rawDescGZIP(), []int{7}
}

func (x *ListOfferV1Request) GetPagination() *PaginationInput {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// ListOfferV1Response ...
type ListOfferV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pagination *PaginationInfo `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Offers     []*Offer        `protobuf:"bytes,2,rep,name=offers,proto3" json:"offers,omitempty"`
}

func (x *ListOfferV1Response) Reset() {
	*x = ListOfferV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListOfferV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOfferV1Response) ProtoMessage() {}

func (x *ListOfferV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOfferV1Response.ProtoReflect.Descriptor instead.
func (*ListOfferV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_offer_api_ocp_offer_api_proto_rawDescGZIP(), []int{8}
}

func (x *ListOfferV1Response) GetPagination() *PaginationInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListOfferV1Response) GetOffers() []*Offer {
	if x != nil {
		return x.Offers
	}
	return nil
}

// UpdateOfferV1Request - update offer `by` id, fields are validated
type UpdateOfferV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Grade  uint64 `protobuf:"varint,3,opt,name=grade,proto3" json:"grade,omitempty"`
	TeamId uint64 `protobuf:"varint,4,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
}

func (x *UpdateOfferV1Request) Reset() {
	*x = UpdateOfferV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOfferV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOfferV1Request) ProtoMessage() {}

func (x *UpdateOfferV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOfferV1Request.ProtoReflect.Descriptor instead.
func (*UpdateOfferV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_offer_api_ocp_offer_api_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateOfferV1Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateOfferV1Request) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateOfferV1Request) GetGrade() uint64 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *UpdateOfferV1Request) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

// UpdateOfferV1Response ...
type UpdateOfferV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateOfferV1Response) Reset() {
	*x = UpdateOfferV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOfferV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOfferV1Response) ProtoMessage() {}

func (x *UpdateOfferV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOfferV1Response.ProtoReflect.Descriptor instead.
func (*UpdateOfferV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_offer_api_ocp_offer_api_proto_rawDescGZIP(), []int{10}
}

// RemoveOfferV1Request - remove offer by `offer_id`. Fields are validated
type RemoveOfferV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OfferId uint64 `protobuf:"varint,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
}

func (x *RemoveOfferV1Request) Reset() {
	*x = RemoveOfferV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveOfferV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveOfferV1Request) ProtoMessage() {}

func (x *RemoveOfferV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveOfferV1Request.ProtoReflect.Descriptor instead.
func (*RemoveOfferV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_offer_api_ocp_offer_api_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveOfferV1Request) GetOfferId() uint64 {
	if x != nil {
		return x.OfferId
	}
	return 0
}

// RemoveOfferV1Response ...
type RemoveOfferV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveOfferV1Response) Reset() {
	*x = RemoveOfferV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveOfferV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveOfferV1Response) ProtoMessage() {}

func (x *RemoveOfferV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveOfferV1Response.ProtoReflect.Descriptor instead.
func (*RemoveOfferV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_offer_api_ocp_offer_api_proto_rawDescGZIP(), []int{12}
}

// PaginationInfo - Contains information about the current state of pagination
type PaginationInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Current page number
	Page uint64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// Total pages
	TotalPages uint64 `protobuf:"varint,2,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	// Total items
	TotalItems uint64 `protobuf:"varint,3,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	// Items per page - max 10k
	PerPage uint32 `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	// Has next page
	HasNextPage bool `protobuf:"varint,5,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	// Has previous page
	HasPreviousPage bool `protobuf:"varint,6,opt,name=has_previous_page,json=hasPreviousPage,proto3" json:"has_previous_page,omitempty"`
}

func (x *PaginationInfo) Reset() {
	*x = PaginationInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaginationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationInfo) ProtoMessage() {}

func (x *PaginationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationInfo.ProtoReflect.Descriptor instead.
func (*PaginationInfo) Descriptor() ([]byte, []int) {
	return file_api_ocp_offer_api_ocp_offer_api_proto_rawDescGZIP(), []int{13}
}

func (x *PaginationInfo) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationInfo) GetTotalPages() uint64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *PaginationInfo) GetTotalItems() uint64 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *PaginationInfo) GetPerPage() uint32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *PaginationInfo) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

func (x *PaginationInfo) GetHasPreviousPage() bool {
	if x != nil {
		return x.HasPreviousPage
	}
	return false
}

// PaginationInput Offset pagination uses skip and take to skip a certain number
// of results and select a limited range. Fields are validated
type PaginationInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Deprecated: Cursor-based pagination uses cursor and take to return a
	// limited set of results before or after a given cursor
	//
	// Deprecated: Do not use.
	Cursor uint64 `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// Number of items per page
	Take uint32 `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	// The number of skipped elements, when using the cursor, the counting starts
	// from the specified id
	Skip uint64 `protobuf:"varint,3,opt,name=skip,proto3" json:"skip,omitempty"`
}

func (x *PaginationInput) Reset() {
	*x = PaginationInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaginationInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationInput) ProtoMessage() {}

func (x *PaginationInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationInput.ProtoReflect.Descriptor instead.
func (*PaginationInput) Descriptor() ([]byte, []int) {
	return file_api_ocp_offer_api_ocp_offer_api_proto_rawDescGZIP(), []int{14}
}

// Deprecated: Do not use.
func (x *PaginationInput) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

func (x *PaginationInput) GetTake() uint32 {
	if x != nil {
		return x.Take
	}
	return 0
}

func (x *PaginationInput) GetSkip() uint64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

var File_api_ocp_offer_api_ocp_offer_api_proto protoreflect.FileDescriptor

var file_api_ocp_offer_api_ocp_offer_api_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x2d,
	0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x2d, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6f, 0x63, 0x70, 0x2e, 0x6f, 0x66, 0x66,
	0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f, 0x0a, 0x05, 0x4f, 0x66, 0x66, 0x65, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x67, 0x72, 0x61,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x67, 0x72, 0x61, 0x64, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x22, 0x79, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x20, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x05, 0x67, 0x72, 0x61, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x05, 0x67, 0x72, 0x61, 0x64,
	0x65, 0x12, 0x20, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x06, 0x74, 0x65, 0x61,
	0x6d, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x66,
	0x65, 0x72, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x58, 0x0a, 0x19,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x65, 0x72,
	0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6f, 0x63, 0x70, 0x2e,
	0x6f, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4f, 0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x06,
	0x6f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x22, 0x32, 0x0a, 0x1a, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3c, 0x0a, 0x16, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x08, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52,
	0x07, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x17, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x22,
	0x5e, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x48, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6f, 0x63, 0x70, 0x2e,
	0x6f, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x8a, 0x01,
	0x02, 0x10, 0x01, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x82, 0x01, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6f, 0x63,
	0x70, 0x2e, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x6f, 0x66, 0x66,
	0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x52, 0x06, 0x6f, 0x66,
	0x66, 0x65, 0x72, 0x73, 0x22, 0x92, 0x01, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f,
	0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02,
	0x20, 0x00, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x05, 0x67, 0x72, 0x61, 0x64,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00,
	0x52, 0x05, 0x67, 0x72, 0x61, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x07, 0x74, 0x65, 0x61, 0x6d, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20,
	0x00, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x3a, 0x0a, 0x14, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4f, 0x66, 0x66, 0x65,
	0x72, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x08, 0x6f, 0x66,
	0x66, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x07, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x49, 0x64, 0x22, 0x17,
	0x0a, 0x15, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xd1, 0x01, 0x0a, 0x0e, 0x50, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x73, 0x12,
	0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x12, 0x19, 0x0a, 0x08, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x68,
	0x61, 0x73, 0x5f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0b, 0x68, 0x61, 0x73, 0x4e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12,
	0x2a, 0x0a, 0x11, 0x68, 0x61, 0x73, 0x5f, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x5f,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x68, 0x61, 0x73, 0x50,
	0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x50, 0x61, 0x67, 0x65, 0x22, 0x6a, 0x0a, 0x0f, 0x50,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1a,
	0x0a, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x02,
	0x18, 0x01, 0x52, 0x06, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x1e, 0x0a, 0x04, 0x74, 0x61,
	0x6b, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x42, 0x0a, 0xfa, 0x42, 0x07, 0x2a, 0x05, 0x18,
	0x90, 0x4e, 0x20, 0x00, 0x52, 0x04, 0x74, 0x61, 0x6b, 0x65, 0x12, 0x1b, 0x0a, 0x04, 0x73, 0x6b,
	0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x28,
	0x00, 0x52, 0x04, 0x73, 0x6b, 0x69, 0x70, 0x32, 0xe9, 0x05, 0x0a, 0x12, 0x4f, 0x63, 0x70, 0x4f,
	0x66, 0x66, 0x65, 0x72, 0x41, 0x70, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x71,
	0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x12,
	0x23, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x6f, 0x66, 0x66, 0x65, 0x72,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x65, 0x72,
	0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x0f, 0x22, 0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x3a, 0x01,
	0x2a, 0x12, 0x86, 0x01, 0x0a, 0x12, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x12, 0x28, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x6f,
	0x66, 0x66, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x29, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x66,
	0x66, 0x65, 0x72, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x15, 0x22, 0x10, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x66, 0x66, 0x65, 0x72,
	0x73, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x3a, 0x01, 0x2a, 0x12, 0x7f, 0x0a, 0x0f, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x12, 0x25, 0x2e,
	0x6f, 0x63, 0x70, 0x2e, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x6f, 0x66, 0x66, 0x65, 0x72,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4f, 0x66, 0x66,
	0x65, 0x72, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x17, 0x12, 0x15, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x73,
	0x2f, 0x7b, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x7d, 0x12, 0x68, 0x0a, 0x0b, 0x4c,
	0x69, 0x73, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x12, 0x21, 0x2e, 0x6f, 0x63, 0x70,
	0x2e, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e,
	0x6f, 0x63, 0x70, 0x2e, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0c, 0x12, 0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x6f,
	0x66, 0x66, 0x65, 0x72, 0x73, 0x12, 0x71, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f,
	0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x12, 0x23, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x6f, 0x66, 0x66,
	0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x66,
	0x65, 0x72, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6f, 0x63,
	0x70, 0x2e, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x1a, 0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x6f,
	0x66, 0x66, 0x65, 0x72, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x79, 0x0a, 0x0d, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x12, 0x23, 0x2e, 0x6f, 0x63, 0x70, 0x2e,
	0x6f, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x4f, 0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24,
	0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x2a, 0x15, 0x2f, 0x76,
	0x31, 0x2f, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x73, 0x2f, 0x7b, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x7d, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6f, 0x7a, 0x6f, 0x6e, 0x63, 0x70, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x6f, 0x66, 0x66,
	0x65, 0x72, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x6f,
	0x66, 0x66, 0x65, 0x72, 0x2d, 0x61, 0x70, 0x69, 0x3b, 0x6f, 0x63, 0x70, 0x5f, 0x6f, 0x66, 0x66,
	0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_ocp_offer_api_ocp_offer_api_proto_rawDescOnce sync.Once
	file_api_ocp_offer_api_ocp_offer_api_proto_rawDescData = file_api_ocp_offer_api_ocp_offer_api_proto_rawDesc
)

func file_api_ocp_offer_api_ocp_offer_api_proto_rawDescGZIP() []byte {
	file_api_ocp_offer_api_ocp_offer_api_proto_rawDescOnce.Do(func() {
		file_api_ocp_offer_api_ocp_offer_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ocp_offer_api_ocp_offer_api_proto_rawDescData)
	})
	return file_api_ocp_offer_api_ocp_offer_api_proto_rawDescData
}

var file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_ocp_offer_api_ocp_offer_api_proto_goTypes = []interface{}{
	(*Offer)(nil),                      // 0: ocp.offer.api.Offer
	(*CreateOfferV1Request)(nil),       // 1: ocp.offer.api.CreateOfferV1Request
	(*CreateOfferV1Response)(nil),      // 2: ocp.offer.api.CreateOfferV1Response
	(*MultiCreateOfferV1Request)(nil),  // 3: ocp.offer.api.MultiCreateOfferV1Request
	(*MultiCreateOfferV1Response)(nil), // 4: ocp.offer.api.MultiCreateOfferV1Response
	(*DescribeOfferV1Request)(nil),     // 5: ocp.offer.api.DescribeOfferV1Request
	(*DescribeOfferV1Response)(nil),    // 6: ocp.offer.api.DescribeOfferV1Response
	(*ListOfferV1Request)(nil),         // 7: ocp.offer.api.ListOfferV1Request
	(*ListOfferV1Response)(nil),        // 8: ocp.offer.api.ListOfferV1Response
	(*UpdateOfferV1Request)(nil),       // 9: ocp.offer.api.UpdateOfferV1Request
	(*UpdateOfferV1Response)(nil),      // 10: ocp.offer.api.UpdateOfferV1Response
	(*RemoveOfferV1Request)(nil),       // 11: ocp.offer.api.RemoveOfferV1Request
	(*RemoveOfferV1Response)(nil),      // 12: ocp.offer.api.RemoveOfferV1Response
	(*PaginationInfo)(nil),             // 13: ocp.offer.api.PaginationInfo
	(*PaginationInput)(nil),            // 14: ocp.offer.api.PaginationInput
}
var file_api_ocp_offer_api_ocp_offer_api_proto_depIdxs = []int32{
	1,  // 0: ocp.offer.api.MultiCreateOfferV1Request.offers:type_name -> ocp.offer.api.CreateOfferV1Request
	0,  // 1: ocp.offer.api.DescribeOfferV1Response.offer:type_name -> ocp.offer.api.Offer
	14, // 2: ocp.offer.api.ListOfferV1Request.pagination:type_name -> ocp.offer.api.PaginationInput
	13, // 3: ocp.offer.api.ListOfferV1Response.pagination:type_name -> ocp.offer.api.PaginationInfo
	0,  // 4: ocp.offer.api.ListOfferV1Response.offers:type_name -> ocp.offer.api.Offer
	1,  // 5: ocp.offer.api.OcpOfferApiService.CreateOfferV1:input_type -> ocp.offer.api.CreateOfferV1Request
	3,  // 6: ocp.offer.api.OcpOfferApiService.MultiCreateOfferV1:input_type -> ocp.offer.api.MultiCreateOfferV1Request
	5,  // 7: ocp.offer.api.OcpOfferApiService.DescribeOfferV1:input_type -> ocp.offer.api.DescribeOfferV1Request
	7,  // 8: ocp.offer.api.OcpOfferApiService.ListOfferV1:input_type -> ocp.offer.api.ListOfferV1Request
	9,  // 9: ocp.offer.api.OcpOfferApiService.UpdateOfferV1:input_type -> ocp.offer.api.UpdateOfferV1Request
	11, // 10: ocp.offer.api.OcpOfferApiService.RemoveOfferV1:input_type -> ocp.offer.api.RemoveOfferV1Request
	2,  // 11: ocp.offer.api.OcpOfferApiService.CreateOfferV1:output_type -> ocp.offer.api.CreateOfferV1Response
	4,  // 12: ocp.offer.api.OcpOfferApiService.MultiCreateOfferV1:output_type -> ocp.offer.api.MultiCreateOfferV1Response
	6,  // 13: ocp.offer.api.OcpOfferApiService.DescribeOfferV1:output_type -> ocp.offer.api.DescribeOfferV1Response
	8,  // 14: ocp.offer.api.OcpOfferApiService.ListOfferV1:output_type -> ocp.offer.api.ListOfferV1Response
	10, // 15: ocp.offer.api.OcpOfferApiService.UpdateOfferV1:output_type -> ocp.offer.api.UpdateOfferV1Response
	12, // 16: ocp.offer.api.OcpOfferApiService.RemoveOfferV1:output_type -> ocp.offer.api.RemoveOfferV1Response
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_ocp_offer_api_ocp_offer_api_proto_init() }
func file_api_ocp_offer_api_ocp_offer_api_proto_init() {
	if File_api_ocp_offer_api_ocp_offer_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Offer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOfferV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOfferV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiCreateOfferV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiCreateOfferV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeOfferV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DescribeOfferV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOfferV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListOfferV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOfferV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOfferV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveOfferV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveOfferV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaginationInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaginationInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ocp_offer_api_ocp_offer_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ocp_offer_api_ocp_offer_api_proto_goTypes,
		DependencyIndexes: file_api_ocp_offer_api_ocp_offer_api_proto_depIdxs,
		MessageInfos:      file_api_ocp_offer_api_ocp_offer_api_proto_msgTypes,
	}.Build()
	File_api_ocp_offer_api_ocp_offer_api_proto = out.File
	file_api_ocp_offer_api_ocp_offer_api_proto_rawDesc = nil
	file_api_ocp_offer_api_ocp_offer_api_proto_goTypes = nil
	file_api_ocp_offer_api_ocp_offer_api_proto_depIdxs = nil
}
